# Generated by Django 4.2.4 on 2023-11-22 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='like_community_users',
            field=models.ManyToManyField(blank=True, related_name='like_communitys', to=settings.AUTH_USER_MODEL),
        ),
    ]
