# Generated by Django 4.2.4 on 2023-11-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_community_like_community_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like_comment_users',
        ),
    ]
