# Generated by Django 4.2.4 on 2023-11-22 05:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0003_remove_comment_like_comment_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like_comment_users',
            field=models.ManyToManyField(blank=True, related_name='like_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
